---
name: 🐛 Bug Report
about: Report a problem or unexpected behavior
title: "[Bug]: "
labels: bug
assignees: ''

---

### Description
A clear and concise description of what the bug is.

### Steps to Reproduce
1. Go to '...'
2. Run the command '...'
3. See error '...'

### Expected Behavior
What did you expect to happen?

### Environment
- OS: [e.g. Windows 10, macOS 13]
- Python version: [e.g. 3.11]
- CLI command used (if applicable): `dice-roller ...`

### Additional Context
Add any other context or screenshots about the problem here.
