---
name: ✨ Feature Request
about: Suggest an idea or enhancement for this project
title: "[Feature]: "
labels: enhancement
assignees: ''

---

### What would you like to see added or changed?
Clearly describe the feature or improvement you have in mind.

### Why is this useful?
Explain how this benefits users or solves a real use case.

### Additional Context
Include examples, links, or sketches if relevant.
