name: Manual Version Bump

on:
  workflow_dispatch:
    inputs:
      level:
        description: "Bump level: patch, minor, or major"
        required: true
        default: "patch"

jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Commitizen
        run: |
          pip install commitizen

      - name: Bump version with Commitizen
        run: |
          cz bump --yes --increment ${{ github.event.inputs.level }}

      - name: Push changes and tags
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git push
          git push --tags
