name: Generate Changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    name: Generate CHANGELOG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          tag: ${{ github.ref_name }}
          futureRelease: ${{ github.ref_name }}

      - name: Commit and Push Changelog
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG for ${{ github.ref_name }}"
          git push
